## Example Config file
baseURL: "https://coldburgundy.github.io/"
theme: "terminalcv"
title: "Draktharr Lab"

params:
  version: "2.0.0"
  description: "My terminal cv"
  blog: true

  prompt:
    core:
      text: "user@DraktharrLab"
      color: "pink"
      before: "["
      beforeColor: "red"
      after: '\]'
      afterColor: "red"
      # separator: '-'
    separator:
      text: "-"
      # color:
    path:
      before: "["
      beforeColor: "red"
      text: "~/home"
      color: "blue"
      after: '\]'
      afterColor: "red"
    extra:
      text: ": "
      color: "orange"

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  listLS: true
  #exitLocation: "about:blank"
  exitMessage: "[Session completed, the browserwindow can be safely closed]"
  source: true
  #use a (blank character) if your first character of the ascii art is a whitespace
  greeting: |
    ________                __      __  .__                          .____          ___.    
    ╲______ ╲____________  │  │ ___╱  │_│  │__ _____ ______________  │    │   _____ ╲_ │__  
    │    │  ╲_  __ ╲__  ╲ │  │╱ ╱╲   __╲  │  ╲╲__  ╲╲_  __ ╲_  __ ╲ │    │   ╲__  ╲ │ __ ╲ 
    │    `   ╲  │ ╲╱╱ __ ╲│    <  │  │ │   Y  ╲╱ __ ╲│  │ ╲╱│  │ ╲╱ │    │___ ╱ __ ╲│ ╲_╲ ╲
    ╱_______  ╱__│  (____  ╱__│_ ╲ │__│ │___│  (____  ╱__│   │__│    │_______ (____  ╱___  ╱
            ╲╱           ╲╱     ╲╱           ╲╱     ╲╱                       ╲╱    ╲╱    ╲╱ 


    Welcome to my online resume

    Type 'help' for a list of available commands

  bootsequence: |
    User request detected
    Reserving Cloud Resources
    ............................
    Cloud Network ready
    ........
    Cloud Instance ready
    .......................
    Internet Breakout Ready, but Pong is preferred 

    Inititating CloudOS
    CloudOS Kernel Version 1.4.2: Sat February 29 23:21:41 CEST 2025; root:xnu-1699.22.73~1/RELEASE_ARM_64
    Loglevel = quiet
    ......
    ............
    ..................
    ........................
    ..............................
    ....................................

    Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
    The Regents of the University of California. All rights reserved.

    Copyright 2024, 2025
    TerminalCV. MIT License (MIT)

    [CloudOSBoot1]: ready
    [CloudOSBoot2]: ready
    [Webserver]: ready 
    [HUGO]: ready
    [TerminalCV]: ready

    Boot Complete, accepting user input.

  whois:
    # settings:
    #   useLess: true
    details:
      name: "Kim"
      profession: "Unknown"
      location: "Somewhere"
      email: "kkkk@cau.ac.kr"
      homelink: "Null"
      description: |
        Just student

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: "github"
        url: "https://github.com"
      - name: "instagram"
        url: "https://instagram.com"

  work:
    # settings:
    #   useLess: true
    details:
      - jobTitle: Job With Red Title
        color: red
        company: "-"
        location: somewhere
        date: August 2010 - Present
        description: Some description about this red title job

      - jobTitle: Job with purple title
        color: purple
        company: "-"
        location: somewhere elese
        date: July 2000  - July 2010
        description: Some description about this purple job

  education:
    details:
      - courseName: Red Color training
        color: red
        date: June 2019 - July 2019
        description: Descrption about red color trianing

      - courseName: Default color training
        date: Sept 2004 - Jun 2008
        #description: There is no need for description

  skills:
    settings:
      useLess: true
    details:
      - name: Skill 1
        percentage: 90
        Description: you can add a description

      - name: Skill 2
        percentage: 30
        #description: or you can leave it comented

      - name: Skill 3
        color: blue
        percentage: 50
        description: Skill names can have colors too

  softskills:
    # settings:
    #   useLess: true
    details:
      - name: SoftSkill 1
        color: red
        percentage: 80
        #description:

      - name: SoftSkill 2
        #color:
        percentage: 90
        description: Description

  languages:
    # settings:
    #   useLess: true
    details:
      - name: English
        color: Blue
        percentage: 50
        #description:

      - name: Gibberish
        percentage: 100
        description: pasghettipigglywiggly

  projects:
    # settings:
    #   useLess: true
    details:
      - title: Project Red
        color: red
        date: since 2019
        link: https://example.com
        description: Describing red stuff

      - title: Project Blue
        color: blue
        date: since 2016
        link: https://example.com/blue
        #description: nothing to describe

      - title: Project Default
        date: Since 2017
        link: https://example.com/default
        #description: not there either

  certifications:
    # settings:
    #   useLess: true
    details:
      - certName: Example Cert
        company: Example Certifying Company
        date: Date of Completion
        badge: https://www.link.to.badge
        #description: Lorem Ipsum

  misc:
    # settings:
    #   useLess: true
    commandName: newcommand
    title: "This Section can have a different command name"
    titleColor: teal
    content: |
      Here the title and the content can have different colors
      The content can be multi

      line

      And spaces       will be respected as well
      This section will have the default command: misc
      but you can name it something else with the property
      commandName: <String>
      Give it a shot and try and uncomment the line 
      commandName: newcommand
      now instead of misc you can execute the newcommand for this section
      Auto completion will know it too! :D

    contentColor: orange

# (1) 코드 하이라이팅 설정 (Chroma)
markup:
  highlight:
    style: "dracula"  # (dracula는 터미널과 어울리는 어두운 테마입니다)
    lineNos: true     # (줄 번호 표시)

# (2) 수학 수식 렌더링 설정 (KaTeX)
  goldmark:
    renderer:
      unsafe: true # (HTML 렌더링을 허용해야 KaTeX가 작동합니다)
outputs:
  home: [ "HTML", "RSS" ]
  page: [ "HTML" ]